server:
  port: 14003

spring:
  application:
    name: config-test
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wanghongqi/springcloudeureka_test
          default-label: master #配置文件分支
          search-paths: config  #配置文件所在根目录
#    bus:
#      enabled: true
#      trace:
#        enabled: true
  rabbitmq:
    host: 192.168.81.161
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh

eureka:
  client:
    service-url:
      defaultZone: http://user:password@10.1.83.108:14001/eureka/