server:
  port: 14003

spring:
  application:
    name: config-test
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wanghongqi/springcloudeureka_test
          default-label: master #配置文件分支
          search-paths: config  #配置文件所在根目录

eureka:
  client:
    service-url:
      defaultZone: http://user:password@10.1.83.108:14001/eureka/